spring:
 application:
  name: "swhatsappemailnotificationservice"
  server:
   port: ${PORT:8080}

whatsapp:
 api:
  url: "https://graph.facebook.com/v22.0/${PHONE_NUMBER_ID}/messages"
  token: ${WHATSAPP_TOKEN}